### ISSUE TITLE
promise_readfile

### ISSUE THREAD

**Issue by azole** [Anthya1104/mfee27-nodejs-workshop#5]
https://github.com/Anthya1104/mfee27-nodejs-workshop/blob/cac61afb22efad50b8c6513d5e509c60ef633971/0806_HW/promise_readfile.js#L30

通常 reject 時，只會把錯誤資料 reject 出來，resolve 時也是，只會把 data resolve 出來，不會幫使用的人決定怎麼用，所以這邊比較合適的做法應該是：

```javascript
function fileReader(filePath, fileType) {
  return new Promise((resolve, reject) => {
    // reject('出錯啦讀不到');
    fs.readFile(filePath, fileType, (err, data) => {
      if (err) {
        return reject(err);
      }
      resolve(data);
    });
  });
}
```

然後由使用者 promise 的人在 then 或 catch 中自行決定怎麼處理

**Comment by yusaanthya** [comment]
原來如此，謝謝老師的建議～
我把promise跟await的寫法改過了，想再麻煩老師有空的時候幫忙看一下現在這樣寫O不OK
